name: Setup Additional Tools
description: |
  Setup additional tools that required for Wasm/NativeAOT tests
  - Node.js
  - V8 with jsvu
  - .NET wasm-tools workload
env:
  NODE_DEBUG: "*"
  npm_config_loglevel: silly
  ACTIONS_STEP_DEBUG: true
runs:
  using: composite
  steps:
    - name: Set up v8
      shell: pwsh
      run: |
        node -v
        Get-ChildItem C:\hostedtoolcache\windows\node
    - name: Set up node
      uses: actions/setup-node@v6
      with:
        node-version: "24.14.0"

    - name: Set up v8
      shell: bash
      run: |
        node -v
        npx jsvu --os=default --engines=javascriptcore

        # Set PATH for jsvu
        $jsvuDir = Join-Path $HOME '.jsvu/bin'
        Add-Content -Path $env:GITHUB_PATH -Value $jsvuDir
        
        # Print paths
        Get-Content $env:GITHUB_PATH -Raw | Write-Host

        # Show extracted results
        Get-ChildItem "$HOME/.jsvu" -Recurse

        # Verify path
        if (-not (Get-Command v8 -CommandType Application -ErrorAction SilentlyContinue)) {
            throw "v8 executable not found."
        }
