name: Setup Additional Tools
description: |
  Setup additional tools that required for Wasm/NativeAOT tests
  - Node.js
  - V8 with jsvu
  - .NET wasm-tools workload
env:
  NODE_DEBUG: "*"
  npm_config_loglevel: silly
  ACTIONS_STEP_DEBUG: true
runs:
  using: composite
  steps:
    - name: Set up node
      uses: actions/setup-node@v6
      with:
        node-version: "24"
        
    - name: Verify
      shell: pwsh
      run: |
        $keys = @(
          'HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome',
          'HKLM:\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome',
          'HKCU:\Software\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome'
        )

        $uninstallString = $null

        foreach ($key in $keys) {
          if (Test-Path $key) {
            $uninstallString = (Get-ItemProperty $key).UninstallString
            if ($uninstallString) {
              break
            }
          }
        }

        if (-not $uninstallString) {
          throw "Chrome uninstall command not found"
        }

        Write-Host "UninstallString: $uninstallString"

        # silent uninstall に変換
        $cmd = $uninstallString `
          -replace '--uninstall', '--uninstall --force-uninstall --silent'

        Start-Process cmd.exe -ArgumentList "/c $cmd" -Wait -NoNewWindow
    - name: Set up v8
      shell: bash
      run: |
        npx jsvu --os=default --engines=v8-debug


        Get-ChildItem $env:Temp/v8-compile-cache -Recurse
         
        # Set PATH for jsvu
        $jsvuDir = Join-Path $HOME '.jsvu/bin'
        Add-Content -Path $env:GITHUB_PATH -Value $jsvuDir
        
        # Print paths
        Get-Content $env:GITHUB_PATH -Raw | Write-Host

        # Show extracted results
        Get-ChildItem "$HOME/.jsvu" -Recurse

        # Verify path
        if (-not (Get-Command v8 -CommandType Application -ErrorAction SilentlyContinue)) {
            throw "v8 executable not found."
        }
