name: Setup Additional Tools
description: |
  Setup additional tools that required for Wasm/NativeAOT tests
  - Node.js
  - V8 with jsvu
  - .NET wasm-tools workload
env:
  NODE_DEBUG: "*"
  npm_config_loglevel: silly
  ACTIONS_STEP_DEBUG: true
runs:
  using: composite
  steps:
    - name: Set up node
      uses: actions/setup-node@v6
      with:
        node-version: "24"

    - name: Set up v8
      shell: pwsh
      run: |
        npm install jsvu -g
        npx jsvu --os=default --engines=v8

        Get-ChildItem "$HOME\.jsvu"

        # Verify d8 command available
        v8 --version

