name: run-tests
run-name: Run tests / ${{ github.event.head_commit.message }}

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
  workflow_dispatch:

env:
  IS_DRAFT_PR: ${{ github.event.pull_request.draft }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:

  test-linux:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      # Build and Test
      - name: Run task 'build'
        run: ./build.cmd build
      - name: Run task 'unit-tests'
        run: ./build.cmd unit-tests -e
