name: run-tests
run-name: Run tests / ${{ github.event.head_commit.message }}

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
  workflow_dispatch:

env:
  IS_DRAFT_PR: ${{ github.event.pull_request.draft }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:

  test-windows-core:
    strategy:
      matrix:
        os: [windows-latest, windows-11-arm]
    runs-on: ${{ matrix.os }}
    steps:
      # Checkout
      - uses: actions/checkout@v6
      # Add Windows Defender Exclusions
      - uses: ./.github/actions/add-windowsdefender-exclusions
      # Setup additional tools
      - name: Setup additional tools for Wasm/NativeAot tests
        if: ${{ github.event.pull_request.draft != true }}
        uses: ./.github/actions/setup-additional-tools
      - name: Test
        shell: pwsh
        if: always()
        run: |
          Get-MpSupportFiles
      # Upload Artifacts with Unique Name
      - name: Upload test results
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: test-windows-core-trx-${{ github.run_id }}-${{ matrix.os }}
          path: |
            C:\ProgramData\Microsoft\Windows Defender\Support\**

  test-windows-full:
    strategy:
      matrix:
        os: [windows-latest, windows-11-arm]
    runs-on: ${{ matrix.os }}
    steps:
      # Checkout
      - uses: actions/checkout@v6
      # Add Windows Defender Exclusions
      - uses: ./.github/actions/add-windowsdefender-exclusions
      # Setup additional tools
      - name: Setup additional tools for Wasm/NativeAot tests
        if: ${{ github.event.pull_request.draft != true }}
        uses: ./.github/actions/setup-additional-tools
      - name: Test
        shell: pwsh
        if: always()
        run: |
          Get-MpSupportFiles
      - name: Upload test results
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: test-windows-full-trx-${{ github.run_id }}-${{ matrix.os }}
          path: |
            C:\ProgramData\Microsoft\Windows Defender\Support\**
