name: run-tests
run-name: Run tests / ${{ github.event.head_commit.message }}

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
  workflow_dispatch:

env:
  IS_DRAFT_PR: ${{ github.event.pull_request.draft }}

jobs:

  test-linux:
    strategy:
      matrix:
        os: [ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      # Build and Test
      - name: Run task 'build'
        run: ./build.cmd build
      - name: Run task 'in-tests-core'
        run: ./build.cmd in-tests-core -e
      # Upload Artifacts with Unique Name
      - name: Upload test results
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: test-linux-trx-${{ github.run_id }}-${{ matrix.os }}
          path: |
            **/*.trx
            **/*.binlog
            **/BenchmarkDotNet.Artifacts/**/*
